In [1]:
import pandas as pd
import numpy as np

In [7]:
#Q1
np.__version__

'1.21.6'

In [11]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')

In [27]:
df.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [12]:
#Q2
df.shape
#Ans : 11914

(11914, 16)

In [35]:
#Q3
df.Make.value_counts().sort_values()
#Ans : Chevrolet, Ford, Volkswagen

Bugatti             3
Genesis             3
Spyker              3
McLaren             5
Alfa Romeo          5
Maybach            16
HUMMER             17
Tesla              18
Lotus              29
Rolls-Royce        31
Lamborghini        52
Maserati           58
Scion              60
FIAT               62
Ferrari            69
Bentley            74
Plymouth           82
Aston Martin       93
Saab              111
Porsche           136
Land Rover        143
Oldsmobile        150
Lincoln           164
Pontiac           186
Chrysler          187
Buick             196
Lexus             202
Mitsubishi        213
Kia               231
Acura             252
Subaru            256
Volvo             281
Hyundai           303
Audi              328
Infiniti          330
BMW               334
Suzuki            351
Mercedes-Benz     353
Cadillac          397
Mazda             423
Honda             449
GMC               515
Nissan            558
Dodge             626
Toyota            746
Volkswagen        809
Ford              881
Chevrolet        1123
Name: Make, dtype: int64

In [26]:
#Q4
df[
    (df['Make'] == 'Audi')
].nunique()
#Ans : 34

Make                   1
Model                 34
Year                  20
Engine Fuel Type       5
Engine HP             40
Engine Cylinders       6
Transmission Type      3
Driven_Wheels          2
Number of Doors        2
Market Category       15
Vehicle Size           3
Vehicle Style          6
highway MPG           23
city mpg              18
Popularity             1
MSRP                 234
dtype: int64

In [14]:
#5
df.isna().sum().sort_values()
#Ans : 5

Make                    0
Model                   0
Year                    0
Transmission Type       0
Driven_Wheels           0
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
Engine Fuel Type        3
Number of Doors         6
Engine Cylinders       30
Engine HP              69
Market Category      3742
dtype: int64

In [36]:
#Q6.1
df["Engine Cylinders"].describe()
#Ans : Median = 6.000000

count    11884.000000
mean         5.628829
std          1.780559
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [37]:
#Q6.2
df["Engine Cylinders"].value_counts().sort_values()
#Ans : 4752 Cars have 4.0 cylinder engines

16.0       3
3.0       30
0.0       56
10.0      68
5.0      225
12.0     230
8.0     2031
6.0     4489
4.0     4752
Name: Engine Cylinders, dtype: int64

In [45]:
#Q6.3 Replacing Missing Values
df["Engine Cylinders"] = df["Engine Cylinders"].fillna(4.0)

In [46]:
df["Engine Cylinders"].isna().sum()

0

In [47]:
#Q6.4 Calculate Median Once again 
df["Engine Cylinders"].describe()
# Median is not Increased

count    11914.000000
mean         5.624727
std          1.780189
min          0.000000
25%          4.000000
50%          6.000000
75%          6.000000
max         16.000000
Name: Engine Cylinders, dtype: float64

In [48]:
#Q7.1
df[
    (df['Make'] == 'Lotus')
]

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
3912,Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,43995
3913,Lotus,Elise,2009,premium unleaded (required),218.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3914,Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3915,Lotus,Elise,2010,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,47250
3916,Lotus,Elise,2010,premium unleaded (required),218.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3917,Lotus,Elise,2011,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,51845
3918,Lotus,Elise,2011,premium unleaded (required),217.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,54990
3919,Lotus,Elise,2011,premium unleaded (required),217.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,26,20,613,57950
4216,Lotus,Esprit,2002,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,89825
4217,Lotus,Esprit,2003,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,90825
4218,Lotus,Esprit,2004,premium unleaded (required),350.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,21,14,613,93225
4257,Lotus,Evora 400,2017,premium unleaded (required),400.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4258,Lotus,Evora 400,2017,premium unleaded (required),400.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,39,21,613,91900
4259,Lotus,Evora,2011,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,27,18,613,64000
4260,Lotus,Evora,2011,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,65500
4261,Lotus,Evora,2013,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,66800
4262,Lotus,Evora,2013,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,77100
4263,Lotus,Evora,2013,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,78600
4264,Lotus,Evora,2013,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,68300
4265,Lotus,Evora,2014,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,78750
4266,Lotus,Evora,2014,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,68750
4267,Lotus,Evora,2014,premium unleaded (required),345.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,17,613,79980
4268,Lotus,Evora,2014,premium unleaded (required),276.0,6.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,18,613,69980
4292,Lotus,Exige,2009,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,74995
4293,Lotus,Exige,2009,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4294,Lotus,Exige,2010,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4295,Lotus,Exige,2011,premium unleaded (recommended),240.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,65690
4296,Lotus,Exige,2011,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,70750
4297,Lotus,Exige,2011,premium unleaded (recommended),257.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,26,20,613,74950

In [51]:
#Q7.2  Select only columns "Engine HP", "Engine Cylinders".
df[["Engine HP","Engine Cylinders"]]

       Engine HP  Engine Cylinders
0          335.0               6.0
1          300.0               6.0
2          300.0               6.0
3          230.0               6.0
4          230.0               6.0
...          ...               ...
11909      300.0               6.0
11910      300.0               6.0
11911      300.0               6.0
11912      300.0               6.0
11913      221.0               6.0

[11914 rows x 2 columns]

In [53]:
# Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])